#ifndef MTCA4U_DMFC_MD22_CONSTANTS_H
#define MTCA4U_DMFC_MD22_CONSTANTS_H

#define SPI_CONTROL_WRITE_ADDRESS_STRING "WORD_SPI_CTRL"
#define SPI_CONTROL_READBACK_ADDRESS_STRING "WORD_SPI_CTRL_B"

#define SMDA_COMMON 0x3
#define JDX_REFERENCE_SWITCH 0xE
#define JDX_CHIP_VERSION 0x9

#define IDX_ACCELERATION_THRESHOLD 0x8
#define ACCELERATION_THRESHOLD_START_BIT 0
#define ACCELERATION_THRESHOLD_STOP_BIT 10
#define CURRENT_SCALING_AT_REST_START_BIT 12
#define CURRENT_SCALING_AT_REST_STOP_BIT 14
#define CURRENT_SCALING_BELOW_THRESHOLD_START_BIT 16
#define CURRENT_SCALING_BELOW_THRESHOLD_STOP_BIT 18
#define CURRENT_SCALING_ABOVE_THRESHOLD_START_BIT 20
#define CURRENT_SCALING_ABOVE_THRESHOLD_STOP_BIT 22

#define IDX_PROPORTIONALITY_FACTORS 0x9
#define DIVISION_PARAMETER_START_BIT 0
#define DIVISION_PARAMETER_STOP_BIT 3
#define MULTIPLICATION_PARAMETER_START_BIT 8
#define MULTIPLICATION_PARAMETER_STOP_BIT 14 

#define RW_WRITE 0
#define RW_READ 1

#endif// MTCA4U_DMFC_MD22_CONSTANTS_H
